name: Verja

on: 
  schedule:
    - cron:  '0 0 16 03 *'
jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: digitalist-se/verja@master
      env:
        CONFIG: config.yml
        CPE: cpe.txt
    - name: done
      run: echo 'done'
